### ISSUE TITLE
Post to npm?

### ISSUE THREAD

**Issue by captbaritone** [Garbee/Eslint-Cross-Browser-Compatibility-Checker#3]
We would like to make use of these rules. Are you planning to publish to npm any time soon, or should we explore making our own solution?

**Comment by Garbee** [comment]
I'm still trying to make sure things work first. I haven't tested putting it into a project yet. Only unit tests, which doesn't show much on if actually plugging it in works.

Once I get some actual usage testing done (I can probably do it later this week) then I'll publish to NPM.

**Comment by captbaritone** [comment]
I'll give it a try against our large-ish code base and let you know if I hit any false positives.

**Comment by Garbee** [comment]
Sweet. Also please just let me know how the actual plugin process is. The README is pre-generated, not sure if anything needs to be tweaked there.

**Comment by captbaritone** [comment]
With the changes in the two pull requests I opened, I was able to get it working as a plugin. Once it was running it found a few instances of each error, and 0 false positives.

**Comment by Garbee** [comment]
Sweet. I'll look into pushing it to NPM tomorrow or Thursday then.

Before I do, I want to decide on whether I should move the main repo over to Gitlab. I'm having some internal issues with the Github monoculture. Which was made even more relevant after this weeks post by big project maintainers asking GH to step-up helping them make projects maintainable. While my repositories aren't big by any means, keeping them primarily in GH still rewards their lack of care to maintainers.

**Comment by captbaritone** [comment]
While I must agree that having so much of open source existing on a closed platform is a bit worrisome, my personal feeling is that GitHub is really doing a remarkable job of embracing an open platform (git) and I don't feel them taking advantage of their monopoly, or trying to wall people/projects in.

I think that for a project this small, distancing yourself from a potential audience may undermine your ability to attract other interested users by an order of magnitude.

My opinion is that the thing that really matters (the code) is tracked in Git and you might as well continue to take advantages that the mono-culture offers (free exposure and convenience), safe in the knowledge that you could easily move to another option if the pain points started to affect you directly.

Obviously you are free to make this decision for yourself, but those are my $0.02.

**Comment by captbaritone** [comment]
Any progress on this?

**Comment by Garbee** [comment]
Sorry, got sick and didn't feel like doing much on computers.

I'm going to move the repo over to GitLab then do the npm push. Just need to get through some stuff with other projects to catch up. Hopefully this will be done this afternoon. If not first thing tomorrow.

Thanks for the patience here, allergies suck.

**Comment by Garbee** [comment]
[Published](https://www.npmjs.com/package/eslint-plugin-cross-browser-compatibility-check)

I'm going to add eslint into the pipeline, then tag a 1.0 once the code style is consistent and tested in future PRs.

[New gitlab repo](https://gitlab.com/garbee/Eslint-Cross-Browser-Compatibility-Checker) where future work will be done. Going to look into mirroring that to GH soon... I don't mind a mirror being here, but I want to try to keep actual development and management over in Gitlab.

Thanks for getting on me to do this @captbaritone! I've kinda just been putting it off as not that important for a while.
